### PR TITLE
Move common code used by cli and tests

### PR DESCRIPTION
**Pull request by lake-of-dreams**
Moved common code used by cli and tests to this repo

### CODE REVIEW

**Review by markxnelson — CHANGES_REQUESTED** [review]
this is introducing unapproved third party dependencies - will not merge this

**Comment by lake-of-dreams** [comment]
changed to
```bash
istio.io/api v0.0.0-20200911191701-0dc35ad5c478
istio.io/client-go v0.0.0-20200807182027-d287a5abb594
k8s.io/api v0.18.6
k8s.io/apimachinery v0.18.6
k8s.io/client-go v0.18.6
```

**Comment by lake-of-dreams** [comment]
refactored further to include `TEST_KUBECONFIG` env var

**Comment by lake-of-dreams** [comment]
closing as the code moved to verrazzano repo

**Pull request closed without merging**
